name: Build and Release Plugin

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Plugin Version
        id: get_version
        run: |
          VERSION=$(grep "Version:" accordion-hero-slider/accordion-hero-slider.php | awk '{print $NF}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "::set-output name=version::$VERSION"

      - name: Create Versioned ZIP
        run: |
          mkdir -p releases
          zip -r releases/accordion-hero-slider-v${{ env.VERSION }}.zip accordion-hero-slider -x "*.DS_Store*" "*.git*"

      - name: Prepare ZIP for PR (Pull Request only)
        if: github.event_name == 'pull_request'
        run: |
          mv releases/accordion-hero-slider-v${{ env.VERSION }}.zip releases/accordion-hero-slider-v${{ env.VERSION }}-PR-${{ github.event.pull_request.number }}.zip

      - name: Upload Build Artifact (PR Only)
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: accordion-hero-slider-PR-${{ github.event.pull_request.number }}
          path: releases/*.zip

      - name: Create Release
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
        uses: softprops/action-gh-release@v2
        with:
          files: releases/accordion-hero-slider-v${{ env.VERSION }}.zip
          tag_name: ${{ startsWith(github.ref, 'refs/tags/v') && github.ref_name || format('v{0}', env.VERSION) }}
          name: Release ${{ env.VERSION }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
